import { normalizeName } from "./playerMatch.mjs";

/** Prefer a specific catalog player when multiple share a surname. */
export const SOURCE_PLAYER_OVERRIDES = {
  "jude bellingham": "129718",
  "ousmane dembele": "153",
  "enzo fernandez": "5996",
  "eden hazard": "2296",
  "morgan gibbs white": "18746",
  "cole palmer": "152982",
  "romelu lukaku": "907",
  "anthony gordon": "138787",
  "fermin lopez": "340626",
  "vitinha": "128384",
  "rasmus hojlund": "288006",
  "joao mario": "206",
  "joe gomez": "284",
  "heung min son": "186",
  "junior kroupi": "368030",
  "eli junior kroupi": "368030",
  "jerome boateng": "3260",
  "alisson": "280",
  "trent alexander arnold": "283",
  "jordan henderson": "292",
  "arturo vidal": "151",
  "luis suarez": "157",
  "arthur melo": "150",
  "nahuel molina": "14007",
  "cristian romero": "30089",
  "theo hernandez": "37888",
  "ederson": "3964",
  "kyle walker": "4041",
  "ferland mendy": "4239",
  "wilfried zaha": "13468",
  "danny ings": "18198",
  "dele alli": "1357",
  "joel matip": "286",
  "danny welbeck": "1469",
  "ollie watkins": "19366",
  "ben brereton diaz": "182617",
};

function retired(name, nationality, age, firstname, lastname) {
  const parts = name.split(" ").filter(Boolean);
  return {
    name,
    firstname: firstname ?? parts[0] ?? name,
    lastname: lastname ?? (parts.slice(1).join(" ") || parts[0] || name),
    age,
    nationality,
    club: "Retired",
    retired: true,
  };
}

/** Retired or missing-from-catalog players used by match lineups and daily lists. */
export const RETIRED_PLAYERS = [
  retired("Ronaldinho", "Brazil", 45, "Ronaldinho", "de Assis"),
  retired("Maicon", "Brazil", 43, "Maicon", "Roque"),
  retired("Dante", "Brazil", 41, "Dante", "Bonfim"),
  retired("Paulinho", "Brazil", 36, "Paulinho", "Vilhena"),
  retired("Luiz Gustavo", "Brazil", 37, "Luiz", "Gustavo"),
  retired("Oscar", "Brazil", 33, "Oscar", "Emboaba"),
  retired("Júlio César", "Brazil", 46, "Julio", "Cesar"),
  retired("Philipp Lahm", "Germany", 41, "Philipp", "Lahm"),
  retired("Benedikt Höwedes", "Germany", 36, "Benedikt", "Howedes"),
  retired("Bastian Schweinsteiger", "Germany", 40, "Bastian", "Schweinsteiger"),
  retired("Miroslav Klose", "Germany", 46, "Miroslav", "Klose"),
  retired("Peter Schmeichel", "Denmark", 61, "Peter", "Schmeichel"),
  retired("Gary Neville", "England", 50, "Gary", "Neville"),
  retired("Jaap Stam", "Netherlands", 52, "Jaap", "Stam"),
  retired("Denis Irwin", "Ireland", 59, "Denis", "Irwin"),
  retired("David Beckham", "England", 49, "David", "Beckham"),
  retired("Nicky Butt", "England", 50, "Nicky", "Butt"),
  retired("Jesper Blomqvist", "Sweden", 49, "Jesper", "Blomqvist"),
  retired("Dwight Yorke", "Trinidad and Tobago", 53, "Dwight", "Yorke"),
  retired("Ronny Johnsen", "Norway", 54, "Ronny", "Johnsen"),
  retired("Oliver Kahn", "Germany", 55, "Oliver", "Kahn"),
  retired("Markus Babbel", "Germany", 53, "Markus", "Babbel"),
  retired("Samuel Kuffour", "Ghana", 48, "Samuel", "Kuffour"),
  retired("Thomas Helmer", "Germany", 59, "Thomas", "Helmer"),
  retired("Lothar Matthäus", "Germany", 63, "Lothar", "Matthaus"),
  retired("Jens Jeremies", "Germany", 51, "Jens", "Jeremies"),
  retired("Stefan Effenberg", "Germany", 57, "Stefan", "Effenberg"),
  retired("Mario Basler", "Germany", 57, "Mario", "Basler"),
  retired("Alexander Zickler", "Germany", 51, "Alexander", "Zickler"),
  retired("Carsten Jancker", "Germany", 51, "Carsten", "Jancker"),
  retired("Bixente Lizarazu", "France", 55, "Bixente", "Lizarazu"),
  retired("Maxwell", "Brazil", 43, "Maxwell", "Santos"),
  retired("Marco Verratti", "Italy", 32, "Marco", "Verratti"),
  retired("Thiago Motta", "Italy", 42, "Thiago", "Motta"),
  retired("Draxler", "Germany", 31, "Julian", "Draxler"),
  retired("Marquinhos", "Brazil", 31, "Marquinhos", "Correa"),
  retired("Emiliano Martínez", "Argentina", 32, "Emiliano", "Martinez"),
  retired("Gael Clichy", "France", 39, "Gael", "Clichy"),
  retired("Fabio Grosso", "Italy", 47, "Fabio", "Grosso"),
  retired("Marco Materazzi", "Italy", 51, "Marco", "Materazzi"),
  retired("Fabio Cannavaro", "Italy", 51, "Fabio", "Cannavaro"),
  retired("Gianluca Zambrotta", "Italy", 47, "Gianluca", "Zambrotta"),
  retired("Andrea Pirlo", "Italy", 45, "Andrea", "Pirlo"),
  retired("Gennaro Gattuso", "Italy", 47, "Gennaro", "Gattuso"),
  retired("Francesco Totti", "Italy", 48, "Francesco", "Totti"),
  retired("Luca Toni", "Italy", 48, "Luca", "Toni"),
  retired("Fabien Barthez", "France", 53, "Fabien", "Barthez"),
  retired("Willy Sagnol", "France", 48, "Willy", "Sagnol"),
  retired("Lilian Thuram", "France", 53, "Lilian", "Thuram"),
  retired("William Gallas", "France", 47, "William", "Gallas"),
  retired("Eric Abidal", "France", 45, "Eric", "Abidal"),
  retired("Claude Makelele", "France", 51, "Claude", "Makelele"),
  retired("Patrick Vieira", "France", 48, "Patrick", "Vieira"),
  retired("Florent Malouda", "France", 44, "Florent", "Malouda"),
  retired("Francesco Toldo", "Italy", 53, "Francesco", "Toldo"),
  retired("Giuseppe Favalli", "Italy", 48, "Giuseppe", "Favalli"),
  retired("Ivan Cordoba", "Colombia", 48, "Ivan", "Cordoba"),
  retired("Sinisa Mihajlovic", "Serbia", 55, "Sinisa", "Mihajlovic"),
  retired("Javier Zanetti", "Argentina", 51, "Javier", "Zanetti"),
  retired("Esteban Cambiasso", "Argentina", 44, "Esteban", "Cambiasso"),
  retired("Cristiano Zanetti", "Italy", 47, "Cristiano", "Zanetti"),
  retired("Dejan Stankovic", "Serbia", 46, "Dejan", "Stankovic"),
  retired("Juan Sebastian Veron", "Argentina", 50, "Juan Sebastian", "Veron"),
  retired("Obafemi Martins", "Nigeria", 40, "Obafemi", "Martins"),
  retired("Julio Cruz", "Argentina", 47, "Julio", "Cruz"),
  retired("Dida", "Brazil", 51, "Dida", "Mark"),
  retired("Alessandro Nesta", "Italy", 48, "Alessandro", "Nesta"),
  retired("Cafu", "Brazil", 54, "Cafu", "Marcos"),
  retired("Clarence Seedorf", "Netherlands", 48, "Clarence", "Seedorf"),
  retired("Kaká", "Brazil", 43, "Kaka", "Santos"),
  retired("Hernán Crespo", "Argentina", 49, "Hernan", "Crespo"),
  retired("Rafinha", "Brazil", 38, "Rafinha", "Alcantara"),
];

export function getSourcePlayerOverride(answer) {
  return SOURCE_PLAYER_OVERRIDES[normalizeName(answer)] ?? null;
}

export function getRetiredPlayer(answer) {
  const key = normalizeName(answer);
  return RETIRED_PLAYERS.find((player) => normalizeName(player.name) === key) ?? null;
}
